# Generated by Django 5.1.15 on 2026-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=160)),
                ('primary_service', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='General', max_length=80),
        ),
        migrations.AlterField(
            model_name='provider',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='providers/'),
        ),
    ]
