# Generated by Django 5.1.15 on 2026-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
