# Generated by Django 5.1.15 on 2026-06-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_provider_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='owner_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ProviderPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='portfolios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='api.provider')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
