# Generated by Django 5.1.15 on 2026-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_provider_is_featured_provider_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='provider',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='providers/profiles/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/'),
        ),
    ]
